spring.application.name=backend
server.port=8081

logging.level.root=INFO

management.trace.http.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/root
spring.datasource.username=root
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.shell.interactive.enabled=true